### ISSUE TITLE
repl: printing without a newline character

### ISSUE THREAD

**Issue by bentxt** [objecthub/swift-lispkit#10]
In lispkits repl you see no result when displaying without a newline. Comparing with other scheme implementation I prefer one of the following two implementations:

1. Prefixing it to the next prompt, like for examples Gambit Schemes repl:
```
> (display "jsd")
jsd>
```

2. Pretty printing the (internal) value of side effects like in the Gauche Schemes repl:

```
gosh> (display "jsd")
jsd#<undef>
gosh>
```

**Comment by objecthub** [comment]
Thanks for catching this bug. The REPL didn't flush the buffered output to the terminal before writing the prompt. I fixed the bug and now the REPL behaves like 2. (i.e. it prints a newline character for your example) if the advanced readline logic is used. This logic can be disabled with flag "-b" (for "basic") which will just use Swift's readLine function and that will result in behavior 1.

Would be great if you could quickly verify that the fix works for you.

**Comment by bentxt** [comment]
that works great, thanks!

**Comment by bentxt** [comment]
sorry, missed the closing comment

**Comment by bentxt** [comment]
everything works great, thanks!
