### ISSUE TITLE
Calling iOS SDKs

### ISSUE THREAD

**Issue by dupuchba** [objecthub/swift-lispkit#12]
First, congratulation for your work ! It's quite amazing.
I am thinking myself about making a small lisp compiler or interpreter and your project helps a lot.

I'd like to know if it's possible to import and call iOS SDKs ?
If so, how did you manage to do it ?

Thanks a lot !
Baptiste

**Comment by objecthub** [comment]
Sorry for my delayed answer. LispKit is a macOS library. I haven't spent much time making this work with iOS. So, it is not possible right now to integrate iOS frameworks.
