### ISSUE TITLE
Threads / Concurrency?

### ISSUE THREAD

**Issue by pepasibble** [objecthub/swift-lispkit#15]
First, this looks amazing!  Thank you so much for working on this (and releasing it!).

I was curious if any form of threads / concurrency is exposed via lispkit?  A quick grep of the codebase only turned up a few `DispatchQueue.main.sync` calls in `Interpreter`.

**Comment by objecthub** [comment]
Concurrency was a big gap so far. My first coroutine-based attempt to implement it failed (like two years ago). I've decided to do something more basic and have just submitted a first version of the new library `(lispkit thread)` based on the [SRFI 18](https://srfi.schemers.org/srfi-18/srfi-18.html) specification. This library is supporting threads, locks, and condition variables.

**Comment by pepasibble** [comment]
oh that's fantastic!  Really impressed by this project.
