### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by bflagg** [objecthub/swift-lispkit#18]
https://github.com/objecthub/swift-lispkit/blob/f2d5a8ac8d606da108d938c4f1d68b4687bd0d28/Sources/LispKit/IO/TextOutput.swift#L152

Calling flush() here seems to cause a double lock() error.

Recommend call flushBuffer() instead.

**Comment by objecthub** [comment]
Thanks a lot for catching this bug, Brian! Have submitted your proposed fix.

**Comment by objecthub** [comment]
The new releases of LispPad and LispPad Go have this bug fix included. Thanks for finding this issue!
