### ISSUE TITLE
bytevector-copy returns range error with less than three arguments 

### ISSUE THREAD

**Issue by jerekapyaho** [objecthub/swift-lispkit#19]
The `bytevector-copy` function always expects three arguments, instead of allowing the last two to be optional. I'm using bytevectors a lot in an application, and it is convenient to pull sections out of them using the 2-argument version, so I happened to notice this. Unless I've completely misunderstood something, then it works different than the documentation.

From LispPad Reference 1.7:

> Returns a newly allocated bytevector containing the bytes in _bytevector_ between _start_ and _end_. If _end_ is not provided, it is assumed to be the length of _bytevector_. If _start_ is not provided, it is assumed to be 0.

However, in LispPad 1.72 on macOS, both the 1-argument and 2-argument versions give range error:

➤ a
#u8(1 2 3 4 5)
➤ (bytevector-copy a)
⚠️ 〚range error〛 expected argument 2 of function bytevector-copy to be an integer value within the range [0, 4]; is 5 instead
 └── (bytevector-copy …) « (<repl> …)
➤ (bytevector-copy a 1)
⚠️ 〚range error〛 expected argument 3 of function bytevector-copy to be an integer value within the range [1, 5]; is 0 instead
 └── (bytevector-copy …) « (<repl> …)
➤ (bytevector-copy a 1 4)
#u8(2 3 4)

I looked at the source code, and I'm not sure I know what is happening to make a pull request, but maybe this turns out to be a quick fix for you.

The LispKit documentation agrees with R7RS, but SRFI 66 doesn't seem to have byte-vector-copy with up to three arguments. 

Possible workaround: compute desired length and index, then use the 3-argument version.

**Comment by jerekapyaho** [comment]
Cross-checked with the GNU Guile documentation: https://www.gnu.org/software/guile/manual/html_node/Bytevector-Procedures-in-R7RS.html

Guile itself gives similar errors with `(import (rnrs bytevectors))`, but works as advertised with `(import (scheme base))`.

**Comment by objecthub** [comment]
Thanks for the bug report! The implementations of `bytevector-copy` and `bytevector-copy!` mixed up start and end parameters. I've fixed that now. I will update this issue once the changes are included in LispPad and LispPad Go.

**Comment by objecthub** [comment]
The latest releases of LispPad and LispPad Go have this error fixed. Will close this issue, but please let me know if there is still something off.

**Comment by objecthub** [comment]
Closing.
