### ISSUE TITLE
How can I run a script

### ISSUE THREAD

**Issue by bentxt** [objecthub/swift-lispkit#21]
Hi
Is there a way to invoke ```.build/debug/LispKitRepl``` with a <script> argument? 
thanks
Ben

**Comment by objecthub** [comment]
Hi Ben, here's an example how you can run a Scheme program via the .build/debug/LispKitRepl binary:

```
.build/debug/LispKitRepl -r Sources/LispKit/Resources --- Sources/LispKit/Resources/Examples/Channels.scm
```

`-r` is followed by potentially several arguments and thus requires some terminator (which is either '---' or another option).

Does this answer your question?

Thanks,
  Matthias

**Comment by objecthub** [comment]
Closing this issue. Let me know if there is still something unclear.
