### ISSUE TITLE
How to interact with native Swift libraries?

### ISSUE THREAD

**Issue by ghost** [objecthub/swift-lispkit#3]
There is something written  in ./Sources/LispKit/Runtime/NativeLibrary.swift

/// 
/// `NativeLibrary` defines a framework for defining built-in functionality for LispKit in
/// a modular fashion. Concrete implementations subclass `NativeLibrary` and override the
/// `export` method with declarations of constants, procedures, and special forms.
///

But that sounds rather abstract, so I'm not quite sure what this does. The thing I'm looking for is sometimes called 'external symbols' or FFI (foreign function interface) in other languages.

**Comment by objecthub** [comment]
Right now, LispKit doesn't have a foreign function interface built in; i.e it is not possible to access, e.g. C-based APIs, without writing Swift code that links them in. `NativeLibrary` would be the superclass of such an adaptor written in Swift.

**Comment by bentxt** [comment]
Ok, is this a example how it works?

./Sources/LispKit/Primitives/CharacterLibrary.swift

```
public final class CharacterLibrary: NativeLibrary {
  
  /// Name of the library.
  public override class var name: [String] {
    return ["lispkit", "character"]
  }
  
  /// Declarations of the library.
   public override func declarations() {
   self.define(Procedure("char?", isChar))
   self.define(Procedure("char=?", charEquals))
   ....
   }
   func charEquals(_ expr: Expr, _ args: Arguments) throws -> Expr {
    ...
   }
}
```

It would be nice if there is a small example of call a Swift function, something like open a small message box.

As this would extend the compiler what could be problematic, I wonder if some kind of a plugin infrastructure would be possible. I'm just learning the ios toolset, so I'm not sure if this would be possible across all architectures, but there is some documentation from apple on this issue: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/LoadingCode/LoadingCode.html


e other thing which I found interesting if it would possible to 

And in addition to that

**Comment by objecthub** [comment]
That's how it works. And I don't really have plans to go beyond. Right now, the main usage is for powering LispPad, a sandboxed macOS application.
