### ISSUE TITLE
LispPad, cannot open file '...'

### ISSUE THREAD

**Issue by jkleiser** [objecthub/swift-lispkit#4]
I am completely new to LispPad. I wanted to try PDF generation, and I ran the PDF.scm. It ended with "pdfex4" in the Console, and when I typed `pdfex1`, I got "#<procedure pdfex1@600000a97b60>", which looks OK to me. However, when I do
```
(pdfex1 "/Volumes/P3/Lisp/ex1.pdf")
```
I get this:
`cannot open file '/Volumes/P3/Lisp/ex1.pdf'`

Why cannot this file be created?

**Comment by objecthub** [comment]
LispPad is a sandboxed application and you cannot write files outside of the sandbox unless you (manually) authorize access. If you just want to create files, I would create them within the sandbox and then simply refer to them from Finder.

For instance, you can create a PDF file like this:

```
(pdfex1 "ex1.pdf")
```

The location of the generated file can be found using the function `file-path`:

```
(file-path "ex1.pdf")
→ "/Users/yourusername/Library/Containers/net.objecthub.LispPad/Data/ex1.pdf"
```

The only other alternative is currently to declare, e.g. your home directory, as a location for libraries via the Preferences (Environment tab). This will give you access to your full home directory bypassing the sandbox. This is obviously a hack. Finding a better solution is currently on my todo list.

**Comment by jkleiser** [comment]
Thanks!

**Comment by jkleiser** [comment]
Maybe the LispPad app could have a menu item that said something like "Open LispPad/Data in Finder"?

**Comment by objecthub** [comment]
The latest version of LispPad has a means to declare a home folder outside of the sandbox. Also the mechanism to persist access to such a folder is working now. Thanks a lot for reporting this issue.
