### ISSUE TITLE
problem with sort

### ISSUE THREAD

**Issue by mbamac** [objecthub/swift-lispkit#6]
sort do not conform to srfi-95.

now is: (sort < list)
should be: (sort list <)

**Comment by objecthub** [comment]
The argument order for function `sort` in SRFI 95 goes back to SRFI 32. I believe there is widespread agreement today, that this historic order of arguments is inconsistent and doesn't fit to the library design of modern R7RS-based Scheme implementations. This is also discussed in SRFI 132 in section "100 SRFIs later...". LispKit adopts the SRFI 132 conventions (and actually also provides a full implementation of SRFI 132). So, this is working as intended.

But thanks a lot for bringing up this topic. I am currently working on documentation. I'll make sure to point this out clearly.
