### ISSUE TITLE
LispPad 1.2.2, included documentation?

### ISSUE THREAD

**Issue by jkleiser** [objecthub/swift-lispkit#7]
When I upgraded LispPad in App Store, to version 1.2.2, I noticed the version info said "now includes the documentation announced already for version 1.2.1". Where can this documentation be found?

**Comment by objecthub** [comment]
You should find the documentation I wrote under item "LispPad Help" of the "Help" menu. Does that work for you? If it doesn't, please let me know. I still didn't figure out how the help book disappeared in version 1.2.1.

**Comment by jkleiser** [comment]
I get a Mac Help page saying "The selected content is currently unavailable". The rest of that page has no info related to LispPad. I tried typing words like "car" and "foldl" in the search field, but that gave me nothing of interest.

**Comment by objecthub** [comment]
Thanks for the investigations! I can reproduce it with a clean installation. Looks like my makefile broke more seriously. I'll fix that and submit a new version next week.

Most of the documentation from the LispPad Help pages can also be found on the LispKit Wiki (just click on the links in the README). Also the LispPad homepage has a version. Sorry for the inconveniences this causes. And thanks again for the bug report.

**Comment by objecthub** [comment]
Apple just approved LispPad 1.2.3. Please let me know if this does not fix the problem for your. Thanks!

**Comment by jkleiser** [comment]
It fixed the problem on one MacBook Air running macOS 10.13.6. On an older Mac mini running macOS 10.14, the 1.2.3 Help fix didn't show right away, but now it's fine. Thanks.
