### ISSUE TITLE
repl: text formatting (color)

### ISSUE THREAD

**Issue by bentxt** [objecthub/swift-lispkit#9]
Not sure if this is a bug, but for me it is unexpected and not ideal behaviour:

The output of the repl is formatted dark. I don't think it matches any of the terminal emulators (iTerm.app, Terminal.app) font color presets.

So if I open the repl in my dark background terminal I don't see the prompt of the repl. Similarly I don't see any of the output of the evaluated expressions.

**Comment by objecthub** [comment]
This wasn't really a bug: the REPL hardcoded black as the color for text input. This is fixed now and the default color is used instead. Now, the REPL should also use readable text with dark backgrounds. Please let me know if that works for you now.

**Comment by bentxt** [comment]
that works great, thanks!
